#!/usr/bin/env groovy
properties([
    parameters([
        string(defaultValue: "master", description: 'Which Git Branch to clone?', name: 'GIT_BRANCH'),
        string(defaultValue: "details", description: 'AWS ECR Repository where built docker images will be pushed.', name: 'ECR_REPO_NAME')
])
])
try
{
  stage('Clone Repo'){
    node('master'){
      cleanWs()
      checkout([$class: 'GitSCM', branches: [[name: '*/$GIT_BRANCH']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'git@gitlab.com:manoj_puc/details.git']]])
    }
  }

  stage('Build Docker Image') {
    node('master'){
      sh "\$(aws ecr get-login --no-include-email --region ap-south-1)"
      GIT_COMMIT_ID = sh (
        script: 'git log -1 --pretty=%H',
        returnStdout: true
      ).trim()
      TIMESTAMP = sh (
        script: 'date +%Y%m%d%H%M%S',
        returnStdout: true
      ).trim()
      echo "Git commit id: ${GIT_COMMIT_ID}"
      IMAGETAG="${GIT_COMMIT_ID}-${TIMESTAMP}"
      sh "docker build -t 645385727312.dkr.ecr.ap-south-1.amazonaws.com/${ECR_REPO_NAME}:${IMAGETAG} ."
      sh "docker push 645385727312.dkr.ecr.ap-south-1.amazonaws.com/${ECR_REPO_NAME}:${IMAGETAG}"
    }
  }

  stage('Deploy on k8s') {
    node('master'){
      withEnv(["KUBECONFIG=${JENKINS_HOME}/.kube/config","IMAGE=645385727312.dkr.ecr.ap-south-1.amazonaws.com/${ECR_REPO_NAME}:${IMAGETAG}"]){
        sh "sed -i 's|IMAGE|${IMAGE}|g' k8s/deployment.yaml"
        sh "kubectl apply -f k8s"
        DEPLOYMENT = sh (
          script: 'cat k8s/deployment.yaml | yq -r .metadata.name',
          returnStdout: true
        ).trim()
        echo "Creating k8s resources..."
        sleep 60
        DESIRED= sh (
          script: "kubectl get deployment/$DEPLOYMENT | awk '{print \$2}' | grep -v DESIRED",
          returnStdout: true
         ).trim()
        CURRENT= sh (
          script: "kubectl get deployment/$DEPLOYMENT | awk '{print \$3}' | grep -v CURRENT",
          returnStdout: true
         ).trim()
        if (DESIRED.equals(CURRENT)) {
          currentBuild.result = "SUCCESS"
          return
        } else {
          error("Deployment Unsuccessful.")
        }
      }
    }
  }
}
catch (err){
  currentBuild.result = "FAILURE"
  throw err
}
